services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_local
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassw0rd!
    ports:
      - "1433:1433"
    build:
      context: .
      dockerfile: Dockerfile

    
